### ISSUE TITLE
Just find it, and do you want to push it to emacs package-list

### ISSUE THREAD

**Issue by beyondpie** [atykhonov/emacs-netspeak#1]
Hi,
I just find this package, and it is started at 2014.
The information from readme seems not enough, and I use it now or it is still in dev ?
Thanks.
Songpeng

**Comment by atykhonov** [comment]
Hi!

It was created mainly for experimentation. It was attempt to answer the question: is it possible to build mostly the same edit facilities as you could see on netspeak.org (i.e. you type `how to ? this` and you get the list (popup) with the suggestions, you can select the word and the question mark is replaced with it). I haven't answered this question yet. It required more work, but unfortunately I hadn't enough time to continue working on it and to finish. 

I just reviewed my local changes and I found that I end up with a lot of [experimentation code](https://github.com/atykhonov/emacs-netspeak/tree/popup) with which I didn't succeed and which I've committed just now. Most likely it is useless for you, but just in case. I don't remember now which exactly issues I was faced. Just remember that it seems I wasn't lucky to manage `auto-complete` to behave in the desired way... For now, I don't use netspeak, hm, but may be get it another chance?

**Comment by atykhonov** [comment]
What do you think? Do you use Emacs and netspeak on regular basis?

**Comment by beyondpie** [comment]
I use Emacs quite often, and only when I write papers (I am not a native speaker of  English), I use netspeak (but not often).  
It is fine for me to use netspeak online. I like Emacs, and I just search it to see if there exists such a package in Emacs.
Thanks for your feedback!
Songpeng

**Comment by atykhonov** [comment]
Btw, try it! Download `netspeak.el` from the master branch, open it in Emacs and `M-x eval-buffer RET`. Then in the `*scratch*` input `how to ? this`, mark (select) it and execute `M-x netspeak-query RET`. Then in the minibuffer you'll see `Netspeak query: how to ? this`, hit `RET` and you'll get new buffer with the completed sentences.

Just let me know how do you think it could be improved so that it would be useful and convenient for you. If the suggested changes would require not much work I'll implement these changes.

Thank you!

**Comment by beyondpie** [comment]
OK ~
I just use it, and it's cool~ It's quite convenient !
Would you mind to think about additional functions, such as:
1. Function of _netspeak-query-line_ to directly query current line instead of select a part of text.
2. Display the words frequencies as in netspeak?
3. Resize default window size of netspeak since most words are not the long.
4. I notice that netspeak add+ button to see cases for such a pattern. It may not so often used.     How do you think  to add this function? For instance, add a link for each pattern so that if we want to see the examples, we can click it or type it in Emacs, then use the browser to show that?

Thank you for this tool !
Songpeng

**Comment by atykhonov** [comment]
> OK ~
> I just use it, and it's cool~ It's quite convenient !

Great! So, let's move forward and try to improve it!

**Comment by atykhonov** [comment]
> 1. Function of netspeak-query-line to directly query current line instead of select a part of text.

Done.

> 1. Display the words frequencies as in netspeak?

Done.

For sorry, you need to download the file again. I'll try in further steps to make the package and publish it on melpa. But, for now it needs to be downloaded.

> 1. Resize default window size of netspeak since most words are not the long.

I didn't get this suggestion. Please clarify.

**Comment by atykhonov** [comment]
Please try implemented functionality and let me know whether everything works fine for now, or how it could be improved even more.

**Comment by beyondpie** [comment]
Hi, 
thanks a lot for your quick reply. 
You can just ignore  _resize default window_ !
I will follow it, and hope you can push it on melpa~
Songpeng
